components:
  - changed-files:
      - any-glob-to-any-file:
          - "components/**"

registry:
  - changed-files:
      - any-glob-to-any-file:
          - "registry/**"

app:
  - changed-files:
      - any-glob-to-any-file:
          - "app/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "guidelines/**"
          - "**/*.md"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.config.*"
          - "tsconfig.json"
          - "package.json"
